name: Pelican site CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Pelican website
      uses: bimbimprasetyoafif/pelican-simple@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Check-out gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages

    - name: Create CNAME file
      run: echo "saocarlos.pyladies.com" > ./gh-pages/CNAME

    - name: Add CNAME file to gh-pages branch
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Add CNAME'
        add: 'CNAME'
        cwd: 'gh-pages'
